PhoneBook/PhoneBookMvc/Controllers/EnterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhoneBookMvc.Controllers
{
    public class EnterController : Controller
    {
        // GET: Enter
        public ActionResult Index()
        {
         
            return View();
        }
       

    }
}

PhoneBook/PhoneBookMvc/Controllers/PhoneBookHomeController.cs
using EntityServices;
using EntityServices.Models;
using EntityServices.Services;
using InfrastructureData;
using PhoneBookMvc.Mappings;
using PhoneBookMvc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PhoneBookMvc.Controllers
{
    public class PhoneBookHomeController : Controller
    {
        protected IContactRepository _contactrepository;

        protected IPhoneNumberReposirory _phonenumberrepository;

        public PhoneBookHomeController(ContactRepository repository, IPhoneNumberReposirory phonenumberrepository)
        {
            this._contactrepository = repository;
            this._phonenumberrepository = phonenumberrepository;
        }

        // GET: PhoneBookHomeController/Contact

        public ActionResult Contacts()
        {
            List<ContactViewModel> cantactsVM = _contactrepository.SelectAll().To_Contact_View_Model().ToList();

            return View(cantactsVM.OrderBy(a => a.FirstName));
        }

        // POST: PhoneBookHomeController/Contact

        [HttpPost]
        public ActionResult Contacts(string searchTerm)
        {
            List<ContactViewModel> cantactsVM = new List<ContactViewModel>();
            if (string.IsNullOrEmpty(searchTerm))
            {
                cantactsVM = _contactrepository.SelectAll().To_Contact_View_Model().ToList();
            }
            else
            {
                cantactsVM = _contactrepository.SelectAll().Where(a => a.FirstName.ToUpper().StartsWith(searchTerm.ToUpper())).To_Contact_View_Model().ToList();
            }

            return View(cantactsVM.OrderBy(a => a.FirstName));
        }

        // POST: PhoneBookHomeController/Autocomplete

        [HttpPost]
        public JsonResult Autocomplete(string Prefix)
        {
            List<string> str;

            str = _contactrepository.SelectAll().Where(a => a.FirstName.ToUpper().StartsWith(Prefix.ToUpper())).Select(b => b.FirstName).ToList();

            return Json(str, JsonRequestBehavior.AllowGet);
        }

        // POST: PhoneBookHomeController/NumberInfo

        public ActionResult NumberInfo(int? id)
        {
            List<PhoneNumber> _phonenumberlist = _phonenumberrepository.SelectAll().Where(d => d.ContactId == id).ToList();

            return View(_phonenumberlist);
        }

        // GET: PhoneBookHomeController/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: PhoneBookHomeController/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContactCreateViewModel contactcreatevm, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                Contact _contact = ContactsMapper.To_Contact_Create_ViewModel(contactcreatevm);
                try
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileName(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/UploadImg"), _FileName);
                        _contact.ImagePath = _FileName;
                        file.SaveAs(_path);
                    }

                }
                catch
                {
                    _contact.ImagePath = "images.png";

                }

                finally
                {
                    int val = 0;
                    _contactrepository.Create(_contact, ref val);
                    _contactrepository.Save();
                    List<PhoneNumber> _phonenumber = PhoneNumberMapper.To_PhoneNumber_Create_ViewModel(contactcreatevm, val).ToList();
                    foreach (PhoneNumber phonItem in _phonenumber)
                    {
                        _phonenumberrepository.Create(phonItem);
                        _phonenumberrepository.Save();
                    }

                }
                return RedirectToAction("Contacts");


            }
            return View("Create");
        }

        // GET: PhoneBookHomeController/Edit

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact _contact = _contactrepository.Select(id);
            List<PhoneNumber> _phonenumberlist = _phonenumberrepository.SelectAll().Where(d => d.ContactId == _contact.ContactId).ToList();
            ContactCreateViewModel contactVM = PhoneNumberMapper.To_Contact_Create_ViewModel(_phonenumberlist);
            contactVM.contactvm = ContactsMapper.To_Contact_View_Model(_contact);
            if (contactVM == null)
            {
                return HttpNotFound();
            }
            return View(contactVM);
        }

        // POST: PhoneBookHomeController/Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContactCreateViewModel contactvmNew, HttpPostedFileBase file)
        {
            try
            {
                Contact _con = ContactsMapper.To_Contact_Create_ViewModel(contactvmNew);
                if (file != null)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadImg"), _FileName);
                    _con.ImagePath = _FileName;
                    file.SaveAs(_path);
                }
                else
                {
                    _con.ImagePath = "images.png";
                }

                _contactrepository.Update(_con);
                _contactrepository.Save();
                List<PhoneNumber> _phonenumber = PhoneNumberMapper.To_PhoneNumber_Create_ViewModel(contactvmNew, _con.ContactId).ToList();
                foreach (PhoneNumber phonItem in _phonenumber)
                {

                    _phonenumberrepository.Update(phonItem);
                    _phonenumberrepository.Save();
                }
                return RedirectToAction("Contacts");
            }
            catch (DataException)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again.");
            }
            return View(contactvmNew);

        }

        //  PhoneBookHomeController/Delete

        public JsonResult Delete(int? id)
        {
            bool result = false;
            Contact _contact = _contactrepository.Select(id);
            List<PhoneNumber> _phonenumberlist = _phonenumberrepository.SelectAll().Where(d => d.ContactId == id).ToList();
            if (_contact != null)
            {
                foreach (PhoneNumber item in _phonenumberlist)
                {
                    _phonenumberrepository.Delete(item.PhoneNumberId);
                    _phonenumberrepository.Save();
                }
                _contactrepository.Delete(id);
                _contactrepository.Save();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _contactrepository.Dispose();
                _contactrepository = null;
                _phonenumberrepository.Dispose();
                _phonenumberrepository = null;
            }
            base.Dispose(disposing);
        }
    }
}

PhoneBook/PhoneBookMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PhoneBook</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/font.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <link rel="stylesheet" href="~/Content/css/style.default.css" id="theme-stylesheet">
    <link rel="stylesheet" href="~/Content/css/custom.css">
    <link rel="shortcut icon" href="~/Content/img/favicon.ico">    
    <link href="~/Content/themes/base/all.css" rel="stylesheet"  />
   
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>


<body>
    <header class="header ">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid d-flex align-items-center justify-content-between">
                <div class="navbar-header">
                    <a href="@Url.Action("Contacts", "PhoneBookHome")" class="navbar-brand">
                        <div class="brand-text brand-big visible text-uppercase"><strong class="text-primary">Phone</strong><strong>Book</strong></div>
                        <div class="brand-text brand-sm"><strong class="text-primary">P</strong><strong>B</strong></div>
                    </a>
                    <button class="sidebar-toggle"><i class="fa fa-long-arrow-left"></i></button>
                </div>
                <ul class="right-menu list-inline no-margin-bottom">
                    <li class="list-inline-item logout"> <a id="logout" href="@Url.Action("Index", "Enter")" class="nav-link">Logout </a></li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="sidebar-header d-flex align-items-center">
                <div class="avatar"><img src="~/Content/img/HovhannisyanA.jpg" alt="..." class="img-fluid rounded-circle"></div>
                <div class="title">
                    <h1 class="h5">Artur Hovhannisyan</h1>
                    <p>.NET DEVELOPER</p>
                </div>
            </div>
            <span class="heading">Main</span>
            <ul class="list-unstyled">
                <li class="active"><a href="@Url.Action("Contacts","PhoneBookHome")">Contacts</a></li>
                <li><a href="@Url.Action("Create","PhoneBookHome")">Create New Contact </a></li>
            </ul>
        </nav>

        <div class="page-content">
            <div class="page-header">
                <div class="container-fluid"></div>
            </div>
            <section class="no-padding-top no-padding-bottom">
                <div class="container-fluid">
                    <div class="statistic-block block">
                        <div class="container body-content">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script language="JavaScript" type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="/js/jquery-ui-personalized-1.5.2.packed.js"></script>
    <script language="JavaScript" type="text/javascript" src="/js/sprinkle.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"> </script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="~/Content/vendor/chart.js/Chart.min.js"></script>
    <script src="~/Scripts/js/charts-home.js"></script>
    <script src="~/Scripts/js/front.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js" ></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
 
</body>
</html>